### ISSUE TITLE
导入clash说配置文件错误

### ISSUE THREAD

**Issue by tkandi** [SubConv/SubConv#70]
发生了如下错误
![image](https://github.com/user-attachments/assets/eb5ba7bd-918d-471a-8288-72a4a191ab2d)
生成的yaml文件开头长这样
```
mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: :9090
dns:
  enable: true
  listen: 0.0.0.0:1053
  default-nameserver:
  - 223.5.5.5
  - 8.8.8.8
  - 1.1.1.1
  nameserver-policy:
    geosite:gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://8.8.8.8/dns-query
    +.zju.edu.cn:
    - 10.10.0.21
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://8.8.8.8/dns-query
```
第15行和第19行分别是`- https://1.1.1.1/dns-query`和`- 10.10.0.21`
是哪里出问题了呢🤔
