### ISSUE TITLE
ruleset这种写法在模板怎么表示？

### ISSUE THREAD

**Issue by gygy** [SubConv/SubConv#72]
模板有如下格式：
```
RULESET:
- - 🤖 ChatBot
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/OpenAi.list
- - 🤖 ChatBot
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/ChatBot.list
```
如下规则，怎么用模板的格式表示
ruleset=🎯 全球直连,[]GEOIP,google-cn

模板直接写会报错
ruleset:
  - 🎯 全球直连: []GEOIP, google-cn

**Comment by wouiSB** [comment]
是clash报错吗

**Comment by gygy** [comment]
> 是clash报错吗

subconv日志报错的

**Comment by wouiSB** [comment]
给出你完整的配置

**Comment by gygy** [comment]
> 给出你完整的配置
配置如下
version: '3'
services:
  subconv:
    image: wouisb/subconv:latest
    container_name: subconv-subconverter
    restart: unless-stopped
    ports:
      - "8183:8080"
    volumes:
      - /app/subconv/config.yaml:/app/config.yaml

config.yaml文件
模板直接写会报错
ruleset:

🎯 全球直连: []GEOIP, google-cn

**Comment by wouiSB** [comment]
报错的config.yaml也发一下

**Comment by gygy** [comment]
错误
```
Error: while parsing a block collection

  in "<unicode string>", line 46, column 3:

    - - 🎯 全球直连

      ^

expected <block end>, but found '<scalar>'

  in "<unicode string>", line 47, column 7:

      - []GEOIP,google-cn

          ^

Error: while parsing a block collection

  in "<unicode string>", line 46, column 3:

    - - 🎯 全球直连

      ^

expected <block end>, but found '<scalar>'

  in "<unicode string>", line 47, column 7:

      - []GEOIP,google-cn
```

文件：
```
HEAD:
  mixed-port: 7890
  allow-lan: true
  mode: rule
  log-level: info
  external-controller: :9090
  dns:
    enable: true
    listen: 0.0.0.0:1053
    default-nameserver:
    - 223.5.5.5
    - 8.8.8.8
    - 1.1.1.1
    nameserver-policy:
      geosite:gfw,geolocation-!cn:
      - https://1.1.1.1/dns-query
      - https://1.0.0.1/dns-query
      - https://8.8.8.8/dns-query
    nameserver:
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
    - https://8.8.8.8/dns-query
    fallback:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://8.8.8.8/dns-query
    fallback-filter:
      geoip: false
      geoip-code: CN
      ipcidr:
      - 240.0.0.0/4
    fake-ip-filter:
    - +.lan
    - +.microsoft*.com
    - localhost.ptlogin2.qq.com
TEST_URL: https://www.gstatic.com/generate_204
RULESET:
- - 🎯 全球直连
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list,28800
- - 🎯 全球直连
  - https://gh-proxy.com/https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Custom_Direct.list,28800
- - 🚀 节点选择
  - https://gh-proxy.com/https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Custom_Proxy.list,28800
- - 🎯 全球直连
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.list,28800
- - 🎯 全球直连
  - []GEOIP,google-cn
- - 🚀 节点选择
  - https://gh-proxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list,28800
- - 🎯 全球直连
  - []GEOIP,category-games@cn
- - 🎯 全球直连
  - https://gh-proxy.com/https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Steam_CDN.list,28800
- - 🎯 全球直连
  - []GEOIP,category-public-tracker
- - 📲 Telegram
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list,28800
- - 🕊️ Twitter(X)
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list,28800
- - 💬 ChatGPT
  - []GEOIP,openai
- - 💬 Copilot
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.list,28800
- - 🤖 AI服务
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Claude/Claude.list,28800
- - 🤖 AI服务
  - []GEOIP,google-gemini
- - 🚀 GitHub
  - []GEOIP,github
- - 🚀 测速工具
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list,28800
- - 📹 YouTube
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list,28800
- - 🎥 AppleTV+
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AppleTV/AppleTV.list,28800
- - 🍎 苹果服务
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list,28800
- - Ⓜ️ 微软服务
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list,28800
- - 🎯 全球直连
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/XiaoMi/XiaoMi.list,28800
- - 📢 谷歌FCM
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list,28800
- - 🇬 谷歌服务
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list,28800
- - 🎶 TikTok
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list,28800
- - 🎥 Netflix
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list,28800
- - 🎥 DisneyPlus
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list,28800
- - 🎥 HBO
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBO/HBO.list,28800
- - 🎥 HBO
  - https://gh-proxy.com/https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/refs/heads/main/rule/HBO_fix.list,28800
- - 🎥 PrimeVideo
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AmazonPrimeVideo/AmazonPrimeVideo.list,28800
- - 🎥 Emby
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Emby/Emby.list,28800
- - 🎥 Emby
  - https://gh-proxy.com/https://raw.githubusercontent.com/ddgksf2013/Filter/refs/heads/master/Emby.list,28800
- - 🎻 Spotify
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list,28800
- - 📺 Bahamut
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list,28800
- - 🎶 网易音乐
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/NetEaseMusic/NetEaseMusic.list,28800
- - 📺 国内媒体
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list,28800
- - 🎯 全球直连
  - https://gh-proxy.com/https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/refs/heads/main/rule/IPTVMainland_Domain.list,28800
- - 🌎 国外媒体
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list,28800
- - 🛒 国外电商
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Amazon/Amazon.list,28800
- - 🛒 国外电商
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AmazonIP/AmazonIP.list,28800
- - 🛒 国外电商
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Shopee/Shopee.list,28800
- - 🛒 国外电商
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Shopify/Shopify.list,28800
- - 🛒 国外电商
  - https://gh-proxy.com/https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/refs/heads/main/rule/Ozon.list,28800
- - 🎮 Steam
  - []GEOIP,steam
- - 🎮 游戏平台
  - []GEOIP,category-games
- - 🚀 节点选择
  - []GEOIP,gfw
- - 🎯 全球直连
  - https://gh-proxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list,28800
- - 🎯 全球直连
  - []GEOIP,cn
- - 🐟 漏网之鱼
  - []FINAL


CUSTOM_PROXY_GROUP:
- name: 🇭🇰 香港节点
  type: url-test
  rule: false
  regex: 香港|香港节点|Honkong
  url: http://cp.cloudflare.com/generate_204
  interval: 300
  timeout: 50
- name: 🇺🇸 美国节点
  type: url-test
  rule: false
  regex: 美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|UnitedStates
  url: http://cp.cloudflare.com/generate_204
  interval: 300
  timeout: 50
- name: 🇯🇵 日本节点
  type: url-test
  rule: false
  regex: 日本|东京|大阪|名古屋|札幌|日本节点
  url: http://cp.cloudflare.com/generate_204
  interval: 300
  timeout: 50
- name: 🇸🇬 新加坡节点
  type: url-test
  rule: false
  regex: 新加坡|新加坡节点
  url: http://cp.cloudflare.com/generate_204
  interval: 300
  timeout: 50
- name: 🇹🇼 台湾节点
  type: url-test
  rule: false
  regex: 台湾|台北|高雄|台湾节点
  url: http://cp.cloudflare.com/generate_204
  interval: 300
  timeout: 50
- name: 🇰🇷 韩国节点
  type: url-test
  rule: false
  regex: 韩国|首尔|釜山|韩国节点
  url: http://cp.cloudflare.com/generate_204
  interval: 300
  timeout: 50
- name: 🇨🇦 加拿大节点
  type: url-test
  rule: false
  regex: 加拿大|温哥华|多伦多|加拿大节点
  url: http://cp.cloudflare.com/generate_204
  interval: 300
  timeout: 50
- name: 🇬🇧 英国节点
  type: url-test
  rule: false
  regex: 英国|伦敦|曼彻斯特|英国节点
  url: http://cp.cloudflare.com/generate_204
  interval: 300
  timeout: 50
- name: 🇫🇷 法国节点
  type: url-test
  rule: false
  regex: 法国|巴黎|马赛|法国节点
  url: http://cp.cloudflare.com/generate_204
  interval: 300
  timeout: 50
- name: 🇩🇪 德国节点
  type: url-test
  rule: false
  regex: 德国|柏林|法兰克福|德国节点
  url: http://cp.cloudflare.com/generate_204
  interval: 300
  timeout: 50
- name: 🇳🇱 荷兰节点
  type: url-test
  rule: false
  regex: 荷兰|阿姆斯特丹|荷兰节点
  url: http://cp.cloudflare.com/generate_204
  interval: 300
  timeout: 50
- name: 🇹🇷 土耳其节点
  type: url-test
  rule: false
  regex: 土耳其|伊斯坦布尔|土耳其节点
  url: http://cp.cloudflare.com/generate_204
  interval: 300
  timeout: 50
- name: 🇻🇳 越南节点
  type: url-test
  rule: false
  regex: 越南|河内|胡志明市|越南节点
  url: http://cp.cloudflare.com/generate_204
  interval: 300
  timeout: 50
- name: 🚀 节点选择
  type: select
  rule: true
  group: [🇭🇰 香港节点, 🇺🇸 美国节点, 🇯🇵 日本节点, 🇸🇬 新加坡节点, 🇹🇼 台湾节点, 🇰🇷 韩国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇳🇱 荷兰节点, 🇹🇷 土耳其节点, 🇻🇳 越南节点]
- name: ♻️ 自动选择
  type: url-test
  rule: false
  regex: .* 
  url: https://cp.cloudflare.com/generate_204
  interval: 300
  timeout: 50
- name: 🎯 全球直连
  type: url-test
  rule: false
  regex: .* 
  url: http://cp.cloudflare.com/generate_204
  interval: 300
  timeout: 50
- name: 🚀 GitHub
  type: select
  rule: true
  group: [🇭🇰 香港节点, 🇺🇸 美国节点, 🇯🇵 日本节点, 🇸🇬 新加坡节点, 🇹🇼 台湾节点, 🇰🇷 韩国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇳🇱 荷兰节点, 🇹🇷 土耳其节点, 🇻🇳 越南节点, 🚀 节点选择, ♻️ 自动选择, 🎯 全球直连]
- name: 📲 Telegram
  type: select
  rule: true
  group: [♻️ 自动选择, 🇭🇰 香港节点, 🇺🇸 美国节点, 🇯🇵 日本节点, 🇸🇬 新加坡节点, 🇹🇼 台湾节点, 🇰🇷 韩国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇳🇱 荷兰节点, 🇹🇷 土耳其节点, 🇻🇳 越南节点, 🚀 节点选择]
- name: 🕊️ Twitter(X)
  type: select
  rule: true
  group: [🇭🇰 香港节点, 🇺🇸 美国节点, 🇯🇵 日本节点, 🇸🇬 新加坡节点, 🇹🇼 台湾节点, 🇰🇷 韩国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇳🇱 荷兰节点, 🇹🇷 土耳其节点, 🇻🇳 越南节点, 🚀 节点选择, ♻️ 自动选择]
- name: 💬 ChatGPT
  type: select
  rule: true
  group: [🇭🇰 香港节点, 🇺🇸 美国节点, 🇯🇵 日本节点, 🇸🇬 新加坡节点, 🇹🇼 台湾节点, 🇰🇷 韩国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇳🇱 荷兰节点, 🇹🇷 土耳其节点, 🇻🇳 越南节点, 🚀 节点选择, ♻️ 自动选择]
- name: 💬 Copilot
  type: select
  rule: true
  group: [🇭🇰 香港节点, 🇺🇸 美国节点, 🇯🇵 日本节点, 🇸🇬 新加坡节点, 🇹🇼 台湾节点, 🇰🇷 韩国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇳🇱 荷兰节点, 🇹🇷 土耳其节点, 🇻🇳 越南节点, 🚀 节点选择, ♻️ 自动选择, 🎯 全球直连]
- name: 🤖 AI服务
  type: select
  rule: true
  group: [🇭🇰 香港节点, 🇺🇸 美国节点, 🇯🇵 日本节点, 🇸🇬 新加坡节点, 🇹🇼 台湾节点, 🇰🇷 韩国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇳🇱 荷兰节点, 🇹🇷 土耳其节点, 🇻🇳 越南节点, 🚀 节点选择, ♻️ 自动选择]
- name: 🎶 TikTok
  type: select
  rule: true
  group: [🇭🇰 香港节点, 🇺🇸 美国节点, 🇯🇵 日本节点, 🇸🇬 新加坡节点, 🇹🇼 台湾节点, 🇰🇷 韩国节点, 🇨🇦 加拿大节点, 🇬🇧 英国节点, 🇫🇷 法国节点, 🇩🇪 德国节点, 🇳🇱 荷兰]
```
